### ISSUE TITLE
.cpython-37m-x86_64-linux-gnu.so: undefined symbol: 

### ISSUE THREAD

**Issue by qujiangang** [mapillary/seamseg#11]
/home/qujiangang/conda/lib/python3.7/site-packages/seamseg/utils/bbx/_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

**Comment by ducksoup** [comment]
Please provide more details about your environment and what you are trying to do. Unfortunately that error message alone is not nearly enough to understand what is going on.

**Comment by HaoLIU94** [comment]
Hello, I met the same error while I was trying to run the inference with the provided pre-trained model (res50).

Traceback (most recent call last):
  File "test_panoptic.py", line 16, in <module>
    import seamseg.models as models
  File "/home/haoliu/.conda/envs/py36/lib/python3.6/site-packages/seamseg/models/__init__.py", line 1, in <module>
    from .resnet import *
  File "/home/haoliu/.conda/envs/py36/lib/python3.6/site-packages/seamseg/models/resnet.py", line 6, in <module>
    from inplace_abn import ABN
  File "/home/haoliu/.conda/envs/py36/lib/python3.6/site-packages/inplace_abn/__init__.py", line 2, in <module>
    from .abn import ABN, InPlaceABN, InPlaceABNSync
  File "/home/haoliu/.conda/envs/py36/lib/python3.6/site-packages/inplace_abn/abn.py", line 6, in <module>
    from .functions import *
  File "/home/haoliu/.conda/envs/py36/lib/python3.6/site-packages/inplace_abn/functions.py", line 5, in <module>
    from . import _backend
I**mportError: /home/haoliu/.conda/envs/py36/lib/python3.6/site-packages/inplace_abn/_backend.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E**

It seems like when we import _backend which is a python compiled file. There is some function definition missing.

This is what I did :
git clone and python setup.py install

python -m torch.distributed.launch --nproc_per_node=1 test_panoptic.py --meta ../model/metadata.bin --log_dir ../log/ ../model/config.ini  ../model/seamseg_r50_vistas.tar /imgs/  ../output/

The requirements are met.

I have:
python 3.6
PyTorch 1.1.0
CUDA 10.1
Ubuntu 18.04 with GCC 7.5

Thanks, if you could help

**Comment by pranshurastogi29** [comment]
hey @HaoLIU94  i am also having same issue have you solved it thanks

**Comment by HaoLIU94** [comment]
> hey @HaoLIU94 i am also having same issue have you solved it thanks

I wasn't able to use this project anyways.
