### ISSUE TITLE
ImportError: ~/anaconda3/lib/python3.7/site-packages/inplace_abn/_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E

### ISSUE THREAD

**Issue by rapires96** [mapillary/seamseg#30]
**Using CUDA 11.3 , PyTorch v1.7, Ubuntu 18.04.5 LTS. While executing:**

python -m torch.distributed.launch --nproc_per_node=1 test_panoptic.py --meta metadata.bin --log_dir ~/logs config.ini seamseg_r50_vistas.tar /home/rapires/images /home/rapires/predictions

**Given the following error. If anyone can provide help it will be much appreciated:**

Traceback (most recent call last):
  File "test_panoptic.py", line 16, in <module>
    import seamseg.models as models
  File "/home/rapires/anaconda3/lib/python3.7/site-packages/seamseg-0.1.dev37+g3d10aea-py3.7-linux-x86_64.egg/seamseg/models/__init__.py", line 1, in <module>
    from .resnet import *
  File "/home/rapires/anaconda3/lib/python3.7/site-packages/seamseg-0.1.dev37+g3d10aea-py3.7-linux-x86_64.egg/seamseg/models/resnet.py", line 6, in <module>
    from inplace_abn import ABN
  File "/home/rapires/anaconda3/lib/python3.7/site-packages/inplace_abn/__init__.py", line 1, in <module>
    from .abn import ABN, InPlaceABN, InPlaceABNSync
  File "/home/rapires/anaconda3/lib/python3.7/site-packages/inplace_abn/abn.py", line 7, in <module>
    from .functions import inplace_abn, inplace_abn_sync
  File "/home/rapires/anaconda3/lib/python3.7/site-packages/inplace_abn/functions.py", line 9, in <module>
    from . import _backend
ImportError: /home/rapires/anaconda3/lib/python3.7/site-packages/inplace_abn/_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E
Traceback (most recent call last):
  File "/home/rapires/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rapires/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rapires/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/rapires/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/rapires/anaconda3/bin/python', '-u', 'test_panoptic.py', '--local_rank=0', '--meta', '/home/rapires/metadata.bin', '--log_dir', '/home/rapires/logs', '/home/rapires/seamseg_vistas/config.ini', '/home/rapires/seamseg_vistas/seamseg_r50_vistas.tar', '/home/rapires/images', '/home/rapires/predictions']' returned non-zero exit status 1.

**Comment by otoofim** [comment]
@rapires96 
I have same problem. Did you figure out how to resolve it?

**Comment by rapires96** [comment]
> @rapires96
> I have same problem. Did you figure out how to resolve it?

Unfortunately not, ended up not using seamseg at all
