### ISSUE TITLE
subprocess.CalledProcessError: Command 

### ISSUE THREAD

**Issue by jianlong-yuan** [mapillary/seamseg#4]
root:/data/research/seamseg-master/scripts# python -m torch.distributed.launch --nproc_per_node=2 train_panoptic.py --log_dir ./log.log "/data/research/seamseg-master/seamseg/config/defaults/panoptic.ini" /common-data/jlong.yuan/segmentation/seamseg/Mapillary/
Traceback (most recent call last):
  File "train_panoptic.py", line 21, in <module>
    from seamseg.config import load_config, DEFAULTS as DEFAULT_CONFIGS
  File "/data/config/anaconda3/lib/python3.6/site-packages/seamseg-3.3.3-py3.6-linux-x86_64.egg/seamseg/config/__init__.py", line 1, in <module>
    from .config import load_config, DEFAULTS
  File "/data/config/anaconda3/lib/python3.6/site-packages/seamseg-3.3.3-py3.6-linux-x86_64.egg/seamseg/config/config.py", line 11, in <module>
    for file in listdir(_DEFAULTS_DIR):
FileNotFoundError: [Errno 2] No such file or directory: '/data/config/anaconda3/lib/python3.6/site-packages/seamseg-3.3.3-py3.6-linux-x86_64.egg/seamseg/config/defaults'
Traceback (most recent call last):
  File "train_panoptic.py", line 21, in <module>
    from seamseg.config import load_config, DEFAULTS as DEFAULT_CONFIGS
  File "/data/config/anaconda3/lib/python3.6/site-packages/seamseg-3.3.3-py3.6-linux-x86_64.egg/seamseg/config/__init__.py", line 1, in <module>
    from .config import load_config, DEFAULTS
  File "/data/config/anaconda3/lib/python3.6/site-packages/seamseg-3.3.3-py3.6-linux-x86_64.egg/seamseg/config/config.py", line 11, in <module>
    for file in listdir(_DEFAULTS_DIR):
FileNotFoundError: [Errno 2] No such file or directory: '/data/config/anaconda3/lib/python3.6/site-packages/seamseg-3.3.3-py3.6-linux-x86_64.egg/seamseg/config/defaults'
Traceback (most recent call last):
  File "/data/config/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/config/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/config/anaconda3/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/data/config/anaconda3/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/data/config/anaconda3/bin/python', '-u', 'train_panoptic.py', '--local_rank=0', '--log_dir', './log.log', '/data/research/seamseg-master/seamseg/config/defaults/panoptic.ini', '/common-data/segmentation/seamseg/Mapillary/']' returned non-zero exit status 1.

**Comment by jianlong-yuan** [comment]
CUDA 9.0 CUDNN 7.1 Pytorch 1.1
do as you say:
git clone https://github.com/mapillary/seamseg.git
cd seamseg
python setup.py install

**Comment by jianlong-yuan** [comment]
CUDA 9.0/10.0  CUDNN 7.1 Pytorch 1.1
do as you say:
git clone https://github.com/mapillary/seamseg.git
cd seamseg
python setup.py install

**Comment by ducksoup** [comment]
This is a weird error, apparently the library has trouble accessing its own installation files. Can you access this directory: `/data/config/anaconda3/lib/python3.6/site-packages/seamseg-3.3.3-py3.6-linux-x86_64.egg/seamseg/config/defaults`?

**Comment by jianlong-yuan** [comment]
There is no /data/config/anaconda3/lib/python3.6/site-packages/seamseg-3.3.3-py3.6-linux-x86_64.egg/seamseg/config/defaults.

**Comment by ducksoup** [comment]
> There is no /data/config/anaconda3/lib/python3.6/site-packages/seamseg-3.3.3-py3.6-linux-x86_64.egg/seamseg/config/defaults.

This is very strange: that path is generated automatically based on the actual location on your system of the installed `seamseg/config/config.py` file. If this points to a non-existing location it could mean that there's something broken in your Python / Anaconda setup.
