### ISSUE TITLE
Expected object of scalar type Byte but got scalar type Bool for argument #2 

### ISSUE THREAD

**Issue by EEEGUI** [mapillary/seamseg#9]
Hello~seamseg is an awesome work!
When I run `panoptic_test.py`,I encountered the following error.Do you know why?Thank you for your answer.
Command :`python -m torch.distributed.launch --nproc_per_node=1 scripts/test_panoptic.py --meta metadata.bin --log_dir test_log config.ini seamseg_r50_vistas.tar test_input test_output`

```
22:09:13 Creating dataloaders for dataset in test_input
22:09:13 Creating backbone model resnet50
22:09:14 Loading snapshot from seamseg_r50_vistas.tar
Traceback (most recent call last):
  File "scripts/test_panoptic.py", line 352, in <module>
    main(parser.parse_args())
  File "scripts/test_panoptic.py", line 348, in main
    make_panoptic=panoptic_preprocessing, num_stuff=meta["num_stuff"])
  File "scripts/test_panoptic.py", line 218, in test
    panoptic_pred = make_panoptic(sem_pred, bbx_pred, cls_pred, obj_pred, msk_pred, num_stuff)
  File "/home/lin/Software/anaconda3/envs/seamseg/lib/python3.6/site-packages/seamseg-0.1.dev27+gb179f47.d20190926-py3.6-linux-x86_64.egg/seamseg/utils/panoptic.py", line 50, in __call__
    intersection = occupied & msk_i
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #2 'other'
Traceback (most recent call last):
  File "/home/lin/Software/anaconda3/envs/seamseg/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lin/Software/anaconda3/envs/seamseg/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lin/Software/anaconda3/envs/seamseg/lib/python3.6/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/lin/Software/anaconda3/envs/seamseg/lib/python3.6/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/lin/Software/anaconda3/envs/seamseg/bin/python', '-u', 'scripts/test_panoptic.py', '--local_rank=0', '--meta', 'metadata.bin', '--log_dir', 'test_log', 'config.ini', 'seamseg_r50_vistas.tar', 'test_input', 'test_output']' returned non-zero exit status 1.
```

**Comment by ducksoup** [comment]
@EEEGUI Are you using Pytorch 1.2?

**Comment by EEEGUI** [comment]
@ducksoup Yes...

**Comment by EEEGUI** [comment]
@ducksoup I  have changed Pytorch 1.2 to Pytorch 1.1, but I encounted this problem.
```
(seamseg) lin@308-ws:~/PycharmProjects/seamseg$ python -m torch.distributed.launch --nproc_per_node=1 scripts/test_panoptic.py --meta metadata.bin --log_dir test_log config.ini seamseg_r50_vistas.tar test_input test_output
Traceback (most recent call last):
  File "scripts/test_panoptic.py", line 16, in <module>
    import seamseg.models as models
  File "/home/lin/Software/anaconda3/envs/seamseg/lib/python3.6/site-packages/seamseg-0.1.dev27+gb179f47-py3.6-linux-x86_64.egg/seamseg/models/__init__.py", line 1, in <module>
    from .resnet import *
  File "/home/lin/Software/anaconda3/envs/seamseg/lib/python3.6/site-packages/seamseg-0.1.dev27+gb179f47-py3.6-linux-x86_64.egg/seamseg/models/resnet.py", line 6, in <module>
    from inplace_abn import ABN
  File "/home/lin/Software/anaconda3/envs/seamseg/lib/python3.6/site-packages/inplace_abn/__init__.py", line 2, in <module>
    from .abn import ABN, InPlaceABN, InPlaceABNSync
  File "/home/lin/Software/anaconda3/envs/seamseg/lib/python3.6/site-packages/inplace_abn/abn.py", line 6, in <module>
    from .functions import *
  File "/home/lin/Software/anaconda3/envs/seamseg/lib/python3.6/site-packages/inplace_abn/functions.py", line 5, in <module>
    from . import _backend
ImportError: /home/lin/Software/anaconda3/envs/seamseg/lib/python3.6/site-packages/inplace_abn/_backend.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
```

**Comment by EEEGUI** [comment]
Reinstalling inplace_abn finished the problem I pasted above.
Thank you for your awesome work.

**Comment by ducksoup** [comment]
@EEEGUI Pytorch 1.2 compatibility is actually in the works, but I'm not sure when we will be able to release it.
